export const Data = [
    {
        title: 'Learning Management System Amikom Center',
        desc: 'Learning management system ini mempunyai fitur Course online, presensi dan pembayaran otomatis yang terintegrasi dengan duitku.com. Build with Vue.js, Bootstrap, Laravel',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948971/project-portfolio/lms_s0qap3.png',
        isProject: false,
        link: 'https://lms.amikomcenter.com',
    },
    {
        title: 'Sistem Informasi Harga dan Produksi Komoditi',
        desc: 'Sistem informasi Harga dan Produksi inflasi Jawa Tengah',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948970/project-portfolio/hargajateng_qu7r3v.png',
        isProject: false,
        link: 'https://dev.hargajateng.org/',
    },
    {
        title: 'Money Changer',
        desc: 'Aplikasi money changer adalah project sewaktu saya magang. Build with Ionic dan Vue.js',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1661512188/project-portfolio/ionic_zcs0jr.png',
        isProject: false,
        link: '#',
    },
    {
        title: 'Dashboard Admin',
        desc: 'Dashboard admin untuk management sebuah website. build with React.js, Tailwind, TypeScript',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/Dashboard_sliidn.png',
        isProject: false,
        link: '#',
    },
    {
        title: 'Sekolahan ID',
        desc: 'Sekolahan ID adalah aplikasi yang memberikan data-data sekolah yang ada di Indonesia. Build with React.js',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/sekolah_nmh3ik.png',
        isProject: false,
        link: 'https://sekolahanid.herokuapp.com/',
    },
    {
        title: 'Extion.go Landing Page',
        desc: 'landing page untuk aplikasi extion.go. Build with Vue.js',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1660036655/project-portfolio/extion_o7i9bm.png',
        isProject: false,
        link: 'https://extion.vercel.app/',
    },
    {
        title: 'Warung Apps',
        desc: 'Project Aplikasi Warung submission Dicoding Front-End Web Developer Expert. Dibuat menggunakan HTML,SCSS,JS dan dibundle menggunakan Webpack udah support PWA',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948973/project-portfolio/warungapp_us5iyj.png',
        isProject: false,
        link: 'https://rofiqurrohman.github.io/',
    },
    {
        title: 'Inventory Management',
        desc: 'Project Aplikasi Perpustakaan akhir tahun event Developer Student Club Jogja. Dibuat menggunakan HTML,SCSS,JS',
        img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/inventory_v5xrqu.png',
        isProject: true,
        link: 'https://github.com/rofiqurrohman/dscjogfest-inventory-management',
    },
]