export const Data = [
  {
    title: 'Fleet Uzzeet',
    desc: 'Fleet Uzzeet adalah web app dari perusahaan PT Telto Telematis Indonesia untuk melacak dan memantau kendaraan, saya terlibat dalam pembuatan beberapa fitur, dibuat dengan vue.js sebagai frontend dan terintegrasi Rest API.',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1700882969/fleet-uzzeet_rn3qwp.png',
    isProject: false,
    link: 'https://fleet.uzzeet.id/',
  },
  {
    title: 'Runner',
    desc: 'Runner adalah sebuah web app yang berbasis GPS Tracking yang di buat oleh perusahaan PT Telto Telematis Indonesia yang dimana saya juga ikut terlibat dalam membuat bebrapa fitur, dibuat dengan vue.js sebagai frontend dan terintegrasi Rest API.',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1700882990/runner_iusvcc.png',
    isProject: false,
    link: 'https://runner.ktbfuso.id/',
  },
  {
    title: 'Sistem Informasi Harga dan Produksi Komoditi',
    desc: 'Sistem informasi Harga dan Produksi inflasi Jawa Tengah (Vue.js, Tailwindcss, Rest API).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948970/project-portfolio/hargajateng_qu7r3v.png',
    isProject: false,
    link: 'https://hargajateng.org/',
  },
  {
    title: 'Learning Management System Amikom Center',
    desc: 'Learning management system ini mempunyai fitur Course online, presensi dan pembayaran otomatis yang terintegrasi dengan duitku.com (Vue.js, Vuex, Tailwindcss, Rest API).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948971/project-portfolio/lms_s0qap3.png',
    isProject: false,
    link: 'https://amikomcenter.com',
  },
  {
    title: 'Money Changer',
    desc: 'Aplikasi money changer (Ionic, TypeScript, Vue.js).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1661512188/project-portfolio/ionic_zcs0jr.png',
    isProject: false,
    link: '#',
  },
  {
    title: 'Dashboard Admin',
    desc: 'Dashboard admin untuk management sebuah website. (React.js, Redux, Tailwindcss, TypeScript).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/Dashboard_sliidn.png',
    isProject: false,
    link: '#',
  },
  {
    title: 'Sekolahan ID',
    desc: 'Sekolahan ID adalah aplikasi yang memberikan data-data sekolah yang ada di Indonesia. (React.js, Recoil.js).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/sekolah_nmh3ik.png',
    isProject: false,
    link: 'https://sekolahanid.herokuapp.com/',
  },
  {
    title: 'Extion.go Landing Page',
    desc: 'landing page untuk aplikasi extion.go. (Vue.js, Bootstrap).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1660036655/project-portfolio/extion_o7i9bm.png',
    isProject: false,
    link: 'https://extion.vercel.app/',
  },
  {
    title: 'Warung Apps',
    desc: 'Project Aplikasi Warung submission Dicoding Front-End Web Developer Expert (HTML, SCSS, JS, Webpack, PWA).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948973/project-portfolio/warungapp_us5iyj.png',
    isProject: false,
    link: 'https://rofiqurrohman.github.io/',
  },
  {
    title: 'Inventory Management',
    desc: 'Project Aplikasi Perpustakaan akhir tahun event Developer Student Club Jogja (HTML, SCSS, JS).',
    img: 'https://res.cloudinary.com/rofiqurrohman/image/upload/v1659948967/project-portfolio/inventory_v5xrqu.png',
    isProject: true,
    link: 'https://github.com/rofiqurrohman/dscjogfest-inventory-management',
  },
];
